kind: pipeline
type: docker
name: build-and-deploy

clone:
  disable: true

steps:
  # - name: clone
  #   image: alpine/git
  #   commands:
  #     - git clone http://gitea.burkcules.burke/burke/budget-dashboard.git
  #     - cd budget-dashboard/
  #     - git checkout $DRONE_COMMIT

  # - name: build
  #   image: node:14
  #   commands:
  #     - cd budget-dashboard/
  #     - unset CI # don't count warnings as errors
  #     - npm install
  #     - npm run build
      
  # - name: test
  #   image: node:14
  #   commands:
  #     - cd budget-dashboard/
  #     - echo "I should implement tests at some point"

  # - name: deploy
  #   image: appleboy/drone-scp
  #   settings:
  #     host: 192.168.1.12
  #     username:
  #       from_secret: SSH_USER
  #     password:
  #       from_secret: SSH_PASSWORD
  #     port: 22
  #     target: /var/www/budget
  #     source: ./budget-dashboard/build/*

  - name: new-file
    image: node:14
    commands:
      - touch test.txt

  - name: scp-test
    image: appleboy/drone-scp
    settings:
      host: 192.168.1.12
      username: test-deploy
      password: testpw
      port: 22
      target: /home/test-deploy
      source: ./test.txt