kind: pipeline
type: docker
name: build-and-deploy

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    commands:
      - git clone http://gitea.burkcules.burke/burke/budget-dashboard.git
      - cd budget-dashboard/
      - git checkout $DRONE_COMMIT

  - name: build
    image: alpine
    commands:
      - cd budget-dashboard/
      - npm install
      - npm run build
      - echo $(whoami)
      - echo "SUCCESS!"